name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Actualiza a la versión compatible con Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v4 # Actualiza a la versión compatible con Node.js 20
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --verbose

    - name: Run tests
      run: |
        python -m unittest discover -s tests
